### ISSUE TITLE
JNDIBypass.jar没办法获取

### ISSUE THREAD

**Issue by boqiqibo** [lemono0/FastJsonParty#1]
师傅，1245-jdk8u342/write-up.md中的JNDIBypass.jar没办法获取，能提供一下吗？或者能说一下用了哪条链子吗？
![image](https://github.com/lemono0/FastJsonParty/assets/67565073/89680596-3710-44b7-b297-05a53fe88427)
我在这个漏洞卡了好久，试了几个工具和利用链都不行。

**Comment by lemono0** [comment]
下载链接已更新，利用原理已在wp中说明了。

**Comment by boqiqibo** [comment]
可以了，感谢师傅。
